#!/usr/bin/env bash


findIgnorePaths=(-not -path '*/.dotfiles/nvim' -not -path '*/.dotfiles/alacritty' -not -path '*/.dotfiles/scripts' -not -path '*/Documents/school' -not -path '*/Documents/programming' -not -path '*Documents/keyboards')
findIgnorePathsLinux=(-not -path '*/.dotfiles/polybar' -not -path '*/.dotfiles/rofi' -not -path '*/.dotfiles/i3')
findIgnorePathsMac=(-not -path '*/.dotfiles/yabai' -not -path '*/.dotfiles/skhd' -not -path '*/.dotfiles/sketchybar')

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/Documents/programming/*/ ~/Documents/ ~/Documents/keyboards/ ~/.dotfiles/ ~/.dotfiles/scripts/.local/  ~/.dotfiles/*/.config/  ~/calendar/calcurse/.local/share/ -mindepth 1 -maxdepth 1 -type d "${findIgnorePaths[@]}" "${findIgnorePathsLinux[@]}" "${findIgnorePathsMac[@]}"| fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
